"""Runtime consequence boundary between financial risk and the Broker.

The GovernedExecutionGateway is the Policy Enforcement Point (PEP) for
consequential trading actions. AIHF may generate an Order, but generation of
an order does not imply authority to execute it.

Every proposed order is submitted to the GovernanceControlPlane before it can
reach the Broker. The control plane evaluates the action against the current
effective authority, which may have been derived from assurance state,
operating context, and stakeholder risk policy.

The gateway deliberately remains separate from the AIHF agents. Agents propose
actions; the governance layer determines whether those actions may cross the
consequence boundary.
"""

from __future__ import annotations

from hedge_fund.brokers.models import Fill, Order
from hedge_fund.brokers.protocol import Broker

from .control import GovernanceControlPlane
from .models import Decision, GovernanceDecision


class GovernedExecutionGateway:
    """Policy Enforcement Point immediately before broker execution.

    The gateway provides the runtime boundary between an AIHF-generated
    trading action and its real or simulated consequence.

    It has three responsibilities:

    1. Submit the proposed Order to the governance control plane for an
       authorization decision.
    2. Prevent DENY and HUMAN_GATE decisions from reaching the Broker
       autonomously.
    3. Verify that the authority epoch used for the authorization decision is
       still current immediately before committing the action.

    The gateway does not determine policy itself. Policy interpretation,
    assurance evaluation, and effective-authority derivation belong to the
    GovernanceControlPlane and the surrounding ACCA components.
    """

    def __init__(
        self,
        broker: Broker,
        governance: GovernanceControlPlane,
        *,
        live: bool = False,
    ):
        """Create a governed broker-execution boundary.

        Args:
            broker:
                The underlying AIHF Broker implementation. The gateway delegates
                to ``broker.place_order`` only after governance authorization.

            governance:
                The GovernanceControlPlane that owns the current effective
                authority and makes the authorization decision.

            live:
                Identifies the consequence type being authorized. ``False``
                evaluates the action as ``paper_order``; ``True`` evaluates it
                as ``live_order``.

                This flag describes the action presented to governance. It is
                intentionally not inferred from the Broker protocol because the
                Broker abstraction itself does not encode governance semantics.
        """
        self.broker = broker
        self.governance = governance
        self.live = live

        # Preserve every governance decision made at this enforcement point.
        # run_cycle() copies these decisions into GovernanceCycleRecord so the
        # authorization behavior is auditable after the cycle completes.
        self.decisions: list[GovernanceDecision] = []

    def place_order(self, order: Order) -> Fill | None:
        """Authorize and, when permitted, execute an AIHF-proposed order.

        The Order has already been generated by the upstream AIHF pipeline:

            analysts/models
                -> signal blending
                -> financial risk limits
                -> order construction
                -> THIS GATEWAY
                -> broker

        Financial risk controls and governance therefore remain distinct.
        ``apply_limits`` determines what portfolio construction considers
        financially acceptable; this gateway determines whether the resulting
        consequential action is currently authorized.

        Returns:
            A Fill when autonomous execution is authorized and the Broker
            successfully executes the order.

            None when governance returns DENY or HUMAN_GATE. HUMAN_GATE is
            intentionally distinguishable from DENY in ``self.decisions`` even
            though neither outcome is allowed to proceed autonomously.

        Raises:
            AuthorityPreempted:
                Indirectly through ``assert_epoch`` if effective authority
                changes after the authorization decision but before the
                irreversible broker commit.
        """

        # ---------------------------------------------------------------
        # Policy Decision
        # ---------------------------------------------------------------
        # Ask the governance control plane whether this specific consequential
        # action is permitted under the CURRENT effective authority.
        #
        # Merely possessing an Order and access to the Broker is therefore not
        # sufficient to execute the trade.
        decision = self.governance.decide_order(
            order,
            live=self.live,
        )

        # Record the decision regardless of outcome. This gives us an audit
        # trail for ALLOW, DENY, and HUMAN_GATE decisions.
        self.decisions.append(decision)

        # ---------------------------------------------------------------
        # Policy Enforcement
        # ---------------------------------------------------------------
        # Only ALLOW may cross the consequence boundary autonomously.
        #
        # DENY:
        #     The action is outside current effective authority.
        #
        # HUMAN_GATE:
        #     The action remains potentially permissible, but autonomous
        #     execution is not currently authorized. A future human-approval
        #     workflow could explicitly resume such an action.
        #
        # Both therefore stop here and never reach broker.place_order().
        if decision.decision != Decision.ALLOW:
            return None

        # ---------------------------------------------------------------
        # Commit-Boundary Epoch Check
        # ---------------------------------------------------------------
        # Authorization is valid only for the authority epoch under which the
        # decision was made.
        #
        # Example:
        #
        #   epoch 7:
        #       order authorized
        #
        #   material change occurs
        #       -> evidence invalidated
        #       -> assurance recomputed
        #       -> authority contracted
        #       -> epoch becomes 8
        #
        #   attempted execution using epoch-7 authorization
        #       -> PREEMPTED
        #
        # This prevents a stale authorization from surviving an intervening
        # material change.
        #
        # With today's synchronous Broker implementations, place_order() is
        # effectively the immediate commit. Future asynchronous, paper, or live
        # adapters should preserve this check as close as possible to the
        # irreversible external action.
        self.governance.assert_epoch(
            decision.authority_epoch
        )

        # ---------------------------------------------------------------
        # Consequence Boundary
        # ---------------------------------------------------------------
        # This is the only path through the gateway that reaches the Broker.
        # At this point:
        #
        #   1. the agent/pipeline proposed the action,
        #   2. governance explicitly authorized it,
        #   3. the authorization epoch is still current.
        #
        # Capability has therefore been separated from permission:
        #
        #       can produce Order != may execute Order
        #
        return self.broker.place_order(order)